# 球队表
CREATE TABLE `live_team` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '名称',
  `image` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '图片',
  `create_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = UTF8 COMMENT = '球队';

# 球员表
CREATE TABLE `live_player` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '名称',
  `image` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '图片',
  `age` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '年龄',
  `team_id` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '球队 ID',
  `position` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '球队位置',
  `create_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = UTF8 COMMENT = '球员';

# 赛事表
CREATE TABLE `live_game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `team_id_1` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '球队 ID1',
  `team_id_2` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '球队 ID2',
  `team_score_1` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '球队分数 1',
  `team_score_2` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '球队分数 2',
  `start_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '开始时间',
  `create_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = UTF8 COMMENT = '赛事';

# 赛况表
CREATE TABLE `live_outs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `game_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '赛事 ID',
  `quarter` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '小节',
  `team_id` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '球队 ID',
  `text` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '文字',
  `image` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '图片',
  `create_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = UTF8 COMMENT = '赛况';

# 用户表
CREATE TABLE `live_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `phone_num` CHAR(11) NOT NULL DEFAULT '' COMMENT '手机号码',
  `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '名称',
  `image` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '图片',
  `create_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = UTF8 COMMENT = '用户';

# 聊天表
CREATE TABLE `live_chat` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `game_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '赛事 ID',
  `user_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户 ID',
  `text` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '文字',
  `create_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = UTF8 COMMENT = '聊天';